// /app/types/initialization.ts
import { ActionType } from './campaign';
import { SuggestedAction } from './campaign';

/**
 * Interface for AI generation results
 * Represents the structure returned from the AI service's content generation
 */
export interface AIGenerationResult {
  /**
   * Narrative text content generated by the AI
   */
  narrative?: string;
  
  /**
   * Suggested actions for the player generated by the AI
   */
  suggestedActions?: Array<{
    id: string;
    title: string;
    description: string;
    type: string;
  }>;
  
  /**
   * Location information generated by the AI
   */
  location?: {
    type: string;
    name?: string;
    description?: string;
  };
}

/**
 * Interface for action items in suggested actions
 * Ensures compatibility with SuggestedAction type
 */
export interface ActionItem extends SuggestedAction {
  id: string;
  title: string;
  description: string;
  type: ActionType;
}
